# This file was generated by GoReleaser. DO NOT EDIT.
cask "setu-agent" do
  version "0.37.0"

  on_macos do
    on_intel do
      sha256 "dd4ab138af71fe61dd3e700e56a7607dedbb758b270c48839131ae83cefe9bde"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
    on_arm do
      sha256 "d59f0c786a22f287fa1d0bc00a2603fc258243de09667bd196b11e54809d9573"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d0d4f7250d0a55dcf87c2e1662c9dc44c4068c4f2457da60fd41c2d5f347657"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
    on_arm do
      sha256 "f0ceee9e959d19be82e94dda07f2e0859fa1602d89a2fcfca03d451268302de1"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
  end

  name "setu-agent"
  desc "Setu edge agent — executes Setu pipeline runs at the edge."
  homepage "https://github.com/Abhishekkumar2021/setu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "setu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/setu"]
    end
  end

  # No zap stanza required

end
