# This file was generated by GoReleaser. DO NOT EDIT.
cask "setu-agent" do
  version "0.45.0"

  on_macos do
    on_arm do
      sha256 "f2a564a25ae7fba6ec1a2d8b9c4a0fb70b975690c76a516fe8fe7c68e8232c5f"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "224cfa63c0c4fa87d04dc92fd60c6d9932c4d9027efa4a86eddb398a731f3a62"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d9e695277d68f2bc94683473e05cd79d9264d1b208e51fcc9aad8f272d9cb141"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f03cf347023a8baea49f67bf1ae154530cd56dcfc595ab93a1d46d40777b55cc"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_linux_amd64.tar.gz"
    end
  end

  name "setu-agent"
  desc "Setu edge agent — executes Setu pipeline runs at the edge."
  homepage "https://github.com/Abhishekkumar2021/setu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "setu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/setu"]
    end
  end

  # No zap stanza required
end
