# This file was generated by GoReleaser. DO NOT EDIT.
cask "setu-agent" do
  version "0.43.0"

  on_macos do
    on_intel do
      sha256 "62b734a26b45c8f670cd78c62710810342707d05be6f8e6922e374b5da73a6eb"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
    on_arm do
      sha256 "4d5621f5d97d735e5628acb3bddcf0b63cbafa36b7a0bb51b3fccca13eda5c4b"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
  end

  on_linux do
    on_intel do
      sha256 "81a2f2d5f4ac700a6273e7f1799010de72c10a8c52542d6b358ac27620aa1d6d"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
    on_arm do
      sha256 "d853b9eeae675252b02fcf93fa25a7ef4aa4f79045d309556e8cef8c1301102a"
      url "https://github.com/Abhishekkumar2021/setu-agent-dist/releases/download/v#{version}/setu-agent_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Abhishekkumar2021/setu-agent-dist"
    end
  end

  name "setu-agent"
  desc "Setu edge agent — executes Setu pipeline runs at the edge."
  homepage "https://github.com/Abhishekkumar2021/setu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "setu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/setu"]
    end
  end

  # No zap stanza required

end
